Kunstmaan/KunstmaanCookieBundle

.github/PULL_REQUEST_TEMPLATE.md
Adds pull request template for github for future contributions
=> [CookieBundle] add pull request template

package-lock.json
Fix npm package vulnerabilities. From the audit report:
`found 13 vulnerabilities (5 low, 8 moderate) in 34797 scanned packages`
=> [CookieBundle] Fix npm package vulnerabilities

README.md, src/Entity/CookieConfig.php, src/EventSubscriber/CookieBarEventSubscriber.php, src/Form/CookieConfigType.php, src/Helper/LegalCookieHelper.php, src/Repository/CookieConfigRepository.php, src/Resources/translations/messages.en.yml, src/Twig/CookieTwigExtension.php
=> Add option to increase version number of cookie consent

src/Helper/LegalCookieHelper.php
=> Check if we have a cookie config

src/Helper/LegalCookieHelper.php
=> Prevent symfony from starting a session when not needed

src/EventSubscriber/CookieBarEventSubscriber.php
=> also add cookie consent when <kuma-cookie-bar> is present in html

src/Resources/ui/scss/components/_btn-toggle.scss, src/Resources/ui/scss/config/_variables.scss, src/Resources/views/Components/CloseCookieModalButton.html.twig, src/Resources/views/Components/CloseDetailButton.html.twig, src/Resources/views/Svg/CloseCookieModalButtonIcon.html.twig, src/Resources/views/Svg/CloseDetailButtonIcon.html.twig
=> fix for issue Kunstmaan#21: Hardcoded img path in sass files

src/Resources/ui/scss/structures/_cookie-bar.scss, src/Resources/views/Components/AcceptAllCookiesButton.html.twig
=> Minor cookiebar styling fixes

README.md
=> fix contributors

src/Generator/LegalGenerator.php, src/Resources/skeleton/legal/DataFixtures/ORM/LegalGenerator/DefaultFixtures.php
| New feature?  |no
| BC breaks?    |no
| Deprecations? |no
=> fixed assets location in sf4

src/Resources/skeleton/legal/Entity/Pages/LegalPage.php, src/Resources/skeleton/legal/Resources/views/Pages/LegalPage/view.html.twig
=> [CookieBundle] Fix symfony 4 incompatibilities

src/Entity/CookieConfig.php
| New feature?  |no
| BC breaks?    |no
| Deprecations? |no
=> fixed error on cookie config save

src/Resources/translations/messages.nl.yml
When using the cms in NL language these translations are missing
=> [CookieBundle] Added missing NL translations

src/Generator/LegalGenerator.php
=> [CookieBunde] Syntax error when generator calls these methods

src/Resources/translations/messages.nl.yml
=> [Cookie-bundle] Fix indentation on messages

src/Resources/skeleton/legal/DataFixtures/ORM/LegalGenerator/DefaultFixtures.php, src/Resources/translations/messages.en.yml, src/Resources/translations/messages.fr.yml, src/Resources/translations/messages.nl.yml
Added missing placeholder for the `legal_cookie`
=> Added extra copy for legal_cookie

src/Twig/CookieTwigExtension.php
=> Don't try to access variable if it's not an array

src/AdminList/CookieAdminListConfigurator.php, src/Controller/CookieAdminListController.php, src/Entity/Cookie.php, src/Form/CookieAdminType.php, src/Resources/config/services.yml, src/Resources/translations/messages.en.yml, src/Resources/translations/messages.nl.yml, src/Resources/views/CookieBar/_detail.html.twig, src/Twig/CookieTwigExtension.php
=> allow selecting for which domain a cookie in the list is relevant

src/Resources/skeleton/legal/Entity/Pages/LegalPage.php
=> Use correct controller notation for legalpage slugaction

src/DependencyInjection/Configuration.php
=> [CookieBundle] Fix symfony config rootNode deprecation

src/DependencyInjection/Configuration.php, src/DependencyInjection/KunstmaanCookieExtension.php, src/Helper/LegalCookieHelper.php
=> Make consent cookie lifetime configurable
